package nexus_event;

import java.util.ArrayList;
import java.util.List;

import nexus_http.Request;
import nexus_http.ResponseReplicate;
import genesis_event.Event;
import genesis_event.EventSelector;
import genesis_event.MultiEventSelector;
import genesis_event.StrictEventSelector;

/**
 * HttpEvents are created by activities around Http requests and responses
 * @author Mikko Hilpinen
 * @since 2.5.2015
 */
public class HttpEvent implements Event
{
	// ATTRIBUTES	---------------------------
	
	private HttpEventType eventType;
	private HttpEventSourceType sourceType;
	private Request request;
	private ResponseReplicate response;
	
	
	// CONSTRUCTOR	---------------------------
	
	/**
	 * Creates a new HttpEvent based on the given request
	 * @param request The request that caused the event
	 * @param type The type of event that was caused
	 */
	public HttpEvent(Request request, HttpEventType type)
	{
		this.eventType = type;
		this.sourceType = HttpEventSourceType.REQUEST;
		this.request = request;
		this.response = null;
	}
	
	/**
	 * Creates a new HttpEvent based on the given response
	 * @param response The response that caused the event
	 * @param type The type of event caused by the response
	 */
	public HttpEvent(ResponseReplicate response, HttpEventType type)
	{
		this.eventType = type;
		this.sourceType = HttpEventSourceType.RESPONSE;
		this.request = null;
		this.response = response;
	}
	
	
	// IMPLEMENTED METHODS	------------------

	@Override
	public List<Event.Feature> getFeatures()
	{
		List<Event.Feature> features = new ArrayList<>();
		features.add(this.eventType);
		features.add(this.sourceType);
		return features;
	}
	
	
	// OTHER METHODS	----------------------
	
	/**
	 * @return The request associated with the event (if applicable)
	 */
	public Request getRequest()
	{
		return this.request;
	}
	
	/**
	 * @return The response associated with the event (if applicable)
	 */
	public ResponseReplicate getResponse()
	{
		return this.response;
	}
	
	/**
	 * @return The type of this event
	 */
	public HttpEventType getEventType()
	{
		return this.eventType;
	}
	
	/**
	 * @return The source of this event
	 */
	public HttpEventSourceType getSourceType()
	{
		return this.sourceType;
	}
	
	/**
	 * Creates a new event selector that will only select events with the given source
	 * @param source The source of the events
	 * @return event selector that will only select event with the given source
	 */
	public static EventSelector<HttpEvent> getEventSelector(HttpEventSourceType source)
	{
		StrictEventSelector<HttpEvent, Feature> selector = new StrictEventSelector<>();
		selector.addRequiredFeature(source);
		return selector;
	}
	
	/**
	 * Creates a new event selector that will only select events with the given type
	 * @param eventType the type of the events
	 * @return event selector that will only select events with the given type
	 */
	public static EventSelector<HttpEvent> getEventSelector(HttpEventType eventType)
	{
		StrictEventSelector<HttpEvent, Feature> selector = new StrictEventSelector<>();
		selector.addRequiredFeature(eventType);
		return selector;
	}
	
	/**
	 * Creates a new event selector that will only select events with the given type and source
	 * @param eventType the type of the events
	 * @param source The source of the events
	 * @return event selector that will only select events with the given type and source
	 */
	public static EventSelector<HttpEvent> getEventSelector(HttpEventType eventType, 
			HttpEventSourceType source)
	{
		StrictEventSelector<HttpEvent, Feature> selector = new StrictEventSelector<>();
		selector.addRequiredFeature(eventType);
		selector.addRequiredFeature(source);
		return selector;
	}
	
	/**
	 * @return An event selector that selects events generated by clients: Sent requests and 
	 * received responses.
	 */
	public static EventSelector<HttpEvent> getClientEventSelector()
	{
		MultiEventSelector<HttpEvent> selector = new MultiEventSelector<>();
		selector.addOption(getEventSelector(HttpEventType.SENT, HttpEventSourceType.REQUEST));
		selector.addOption(getEventSelector(HttpEventType.RECEIVED, 
				HttpEventSourceType.RESPONSE));
		
		return selector;
	}
	
	/**
	 * @return An event selector that selects events generated by servers: Received requests 
	 * and sent responses.
	 */
	public static EventSelector<HttpEvent> getServerEventSelector()
	{
		MultiEventSelector<HttpEvent> selector = new MultiEventSelector<>();
		selector.addOption(getEventSelector(HttpEventType.RECEIVED, 
				HttpEventSourceType.REQUEST));
		selector.addOption(getEventSelector(HttpEventType.SENT, HttpEventSourceType.RESPONSE));
		
		return selector;
	}

	
	// INTERFACES	---------------------------
	
	/**
	 * A wrapper for features of HttpEvents
	 * @author Mikko Hilpinen
	 * @since 2.5.2015
	 */
	public static interface Feature extends Event.Feature
	{
		// This interface is used as a wrapper
	}
	
	
	// ENUMERATIONS	---------------------------
	
	/**
	 * Http events can be created by sent or received data
	 * @author Mikko Hilpinen
	 * @since 2.5.2015
	 */
	public static enum HttpEventType implements Feature
	{
		/**
		 * Events with this feature are created when data is sent
		 */
		SENT,
		/**
		 * Events with this feature are created when data is received
		 */
		RECEIVED;
	}
	
	/**
	 * Http events can be caused by either http requests or http responses
	 * @author Mikko Hilpinen
	 * @since 2.5.2015
	 */
	public static enum HttpEventSourceType implements Feature
	{
		/**
		 * Events with this feature are caused by http requests
		 */
		REQUEST,
		/**
		 * Events with this feature are caused by http responses
		 */
		RESPONSE;
	}
}
